package domain;
// Generated 2016-09-21 11:06:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Game generated by hbm2java
 */
public class Game  implements java.io.Serializable {


     private int id;
     private GameStatus gameStatus;
     private String whiteKey;
     private String blackKey;
     private Long whiteTime;
     private Long blackTime;
     private Boolean onMove;
     private String gameKey;
     private Date createdOn;

    public Game() {
    }

	
    public Game(int id, GameStatus gameStatus, String whiteKey, String blackKey, String gameKey) {
        this.id = id;
        this.gameStatus = gameStatus;
        this.whiteKey = whiteKey;
        this.blackKey = blackKey;
        this.gameKey = gameKey;
    }
    public Game(int id, GameStatus gameStatus, String whiteKey, String blackKey, Long whiteTime, Long blackTime, Boolean onMove, String gameKey, Date createdOn) {
       this.id = id;
       this.gameStatus = gameStatus;
       this.whiteKey = whiteKey;
       this.blackKey = blackKey;
       this.whiteTime = whiteTime;
       this.blackTime = blackTime;
       this.onMove = onMove;
       this.gameKey = gameKey;
       this.createdOn = createdOn;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public GameStatus getGameStatus() {
        return this.gameStatus;
    }
    
    public void setGameStatus(GameStatus gameStatus) {
        this.gameStatus = gameStatus;
    }
    public String getWhiteKey() {
        return this.whiteKey;
    }
    
    public void setWhiteKey(String whiteKey) {
        this.whiteKey = whiteKey;
    }
    public String getBlackKey() {
        return this.blackKey;
    }
    
    public void setBlackKey(String blackKey) {
        this.blackKey = blackKey;
    }
    public Long getWhiteTime() {
        return this.whiteTime;
    }
    
    public void setWhiteTime(Long whiteTime) {
        this.whiteTime = whiteTime;
    }
    public Long getBlackTime() {
        return this.blackTime;
    }
    
    public void setBlackTime(Long blackTime) {
        this.blackTime = blackTime;
    }
    public Boolean getOnMove() {
        return this.onMove;
    }
    
    public void setOnMove(Boolean onMove) {
        this.onMove = onMove;
    }
    public String getGameKey() {
        return this.gameKey;
    }
    
    public void setGameKey(String gameKey) {
        this.gameKey = gameKey;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }




}


