package domain;
// Generated 2016-09-21 11:06:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GameStatus generated by hbm2java
 */
public class GameStatus  implements java.io.Serializable {


     private int id;
     private String name;
     private Set games = new HashSet(0);

    public GameStatus() {
    }

	
    public GameStatus(int id) {
        this.id = id;
    }
    public GameStatus(int id, String name, Set games) {
       this.id = id;
       this.name = name;
       this.games = games;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getGames() {
        return this.games;
    }
    
    public void setGames(Set games) {
        this.games = games;
    }




}


